### ISSUE TITLE
Couldn't find dll file  libGemmQnnAie_8x2048_2048x2048.dll

### ISSUE THREAD

**Issue by jens-ajisai** [ahoquegh/Chatbot-with-RyzenAI-1.0#3]
I followed the instructions. However, I need a clarification on the setup.

>Clone this repo or download and extract Chatbot-with-RyzenAI-1.0.zip into the root directory where you have installed the Ryzen AI SW.

This means the "example\transformers\" subfolder in the RyzenAI-SW installation, right?

And for
> Activate the conda environment created when RyzenAI was installed.
It is required to activate the conda environment created with the instructions for the transformers example, right?

I get the following error for step 3

```I20240519 16:53:06.503293  7336 vitisai_compile_model.cpp:361]   present.23.key : [-1x32x-1x64]
I20240519 16:53:06.503293  7336 vitisai_compile_model.cpp:361]   present.23.value : [-1x32x-1x64]
C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\voe\passes\fuse_GEMM.py:62: RuntimeWarning: invalid value encountered in divide
  weight_q = np.clip(np.round(weight_f / weight_scale), -128, 127).astype(np.int8)
C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\voe\passes\fuse_GEMM.py:62: RuntimeWarning: invalid value encountered in cast
  weight_q = np.clip(np.round(weight_f / weight_scale), -128, 127).astype(np.int8)
Couldn't find dll file  libGemmQnnAie_8x2048_2048x2048.dll,
F20240519 16:53:07.404875  7336 pass_main.cpp:68] SystemExit: <EMPTY MESSAGE>

At:
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\voe\passes\fuse_GEMM.py(100): action
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\voe\rule_ext\__init__.py(81): _action
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py(435): _create_inference_session
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py(383): __init__
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_ort.py(369): load_model
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_decoder.py(536): _from_pretrained
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\modeling_base.py(372): from_pretrained
  C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_ort.py(622): from_pretrained
  c:\tools\RyzenAI-SW\example\transformers\run.py(106): <module>
[Vitis AI EP] No. of Operators :   CPU  2106
I20240519 16:53:07.467839  7336 vitisai_compile_model.cpp:376] Catch fatal exception, skip this subgraph. Set XLNX_ENABLE_SKIP_FATAL=0 to stop skip.
attrs_create_cif
```

There is a file libGemmQnnAie_8x2048_2048x2048.dll in the "RyzenAI-SW\example\transformers\dll\phx\qlinear\". There are multiple files in other folders under the dll folder. I tried to add them to the PATH, but I keep getting this issue.

The results is that it runs only on CPU.

**Comment by jens-ajisai** [comment]
After adding
```
set TVM_MODULE_PATH=%~dp0\dll\%DEVICE%\qlinear\libGemmQnnAie_1x2048_2048x2048.dll,%~dp0\dll\%DEVICE%\qlinear\libGemmQnnAie_8x2048_2048x2048.dll,
set TVM_GEMM_M=1,8,
set TVM_DLL_NUM=2
```
as it was done in https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/models/opt-onnx/set_opt_onnx_env.bat

this issue went away.

And the next issue appeared
```
I20240520 12:12:50.257315 13340 vitisai_compile_model.cpp:361]   present.31.key : [-1x32x-1x128]
I20240520 12:12:50.257315 13340 vitisai_compile_model.cpp:361]   present.31.value : [-1x32x-1x128]
C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\voe\passes\fuse_MATMUL.py:56: RuntimeWarning: invalid value encountered in divide
  weight_q = np.clip(np.round(weight_f / weight_scale), -128, 127).astype(
C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\voe\passes\fuse_MATMUL.py:56: RuntimeWarning: invalid value encountered in cast
  weight_q = np.clip(np.round(weight_f / weight_scale), -128, 127).astype(
[Vitis AI EP] No. of Operators :   CPU  2615   GEMM   225
[Vitis AI EP] No. of Subgraphs :  GEMM   225
2024-05-20 12:24:17.2183642 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-05-20 12:24:17.2289439 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[libprotobuf FATAL C:\Users\xbuild\Desktop\xj3\VAI_RT_WIN_ONNX_EP_ALL\install_dir\include\google/protobuf/map.h:1293] CHECK failed: it != end(): key not found: in_scale
2024-05-20 12:24:17.3363517 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_7886affda615b201aacee9192bb1c95a>::operator ()] Exception during initialization: CHECK failed: it != end(): key not found: in_scale
Traceback (most recent call last):
  File "c:\tools\RyzenAI-SW\example\transformers\run.py", line 126, in <module>
    model = ORTModelForCausalLM.from_pretrained(path, provider=provider,use_cache=args.disable_cache, use_io_binding=False, provider_options=provider_options)
  File "C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 622, in from_pretrained
    return super().from_pretrained(
  File "C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_decoder.py", line 536, in _from_pretrained
    model = ORTModel.load_model(
  File "C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 369, in load_model
    return ort.InferenceSession(
  File "C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\tools\anaconda3\envs\ryzenai-transformers\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: CHECK failed: it != end(): key not found: in_scale
2024-05-20 12:24:18.0563894 [W:onnxruntime:Default, vitisai_execution_provider.cc:74 onnxruntime::VitisAIExecutionProvider::~VitisAIExecutionProvider] Releasing the FlexML EP pointer in Vitis AI EP
```

Note that I modified the example to use llama2 for which also a smoothquant file is available.

Can you say if these steps are required too?
https://github.com/amd/RyzenAI-SW/blob/main/example/transformers/models/opt-onnx/prepare_model.bat line 5-7.
